# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cae7e7d0d28f2dcc6c4614a58e81c63166b17012c26ba3198a0bc13884182e09db9eba190ba479d65ef96ebca6354bd63f9f970c03065acfde9cf58efdab746e
  mailer_username: <%= ENV["MAILER_USERNAME"] %>
  mailer_password: <%= ENV["MAILER_PASSWORD"] %>
  mailer_address: <%= ENV["MAILER_ADDRESS"] %>
  mailer_domain: <%= ENV["MAILER_DOMAIN"] %>
  mailer_port: <%= ENV["MAILER_PORT"] %>

test:
  secret_key_base: 9f443a2352443b5da1f43b60a9de868905b7141f50212afac7fe73e4bb4a5b6d61b6830e573b319c64f0e749697aeb8e7f8377bc39508b621887323d91e1cb17

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
